### ISSUE TITLE
Enable multiple accounts in a single device

### ISSUE THREAD

**Issue by segunfrancis** [theDroidCamp/Local-Storage#3]
I'd like to be able to sign up with my 2 different email addresses without the second one over writing the first. 
Example: 1st account has the following details

> Name - Segun Francis 

> email - segunfrancis@yahoo.com

> school - university of Port Harcourt 

> password - password

2nd account has the following details

> Name - Segun Francis

> email - segunfrancis@gmail.com

> school - university of Ilorin

> password - password

I want a situation whereby I can have both accounts existing in the app so that whichever email address i use to login, I'll get the appropriate details associated with that email address

**Comment by GodfirstOnuoha** [comment]
Should we still use SharedPreference to achieve this?

**Comment by segunfrancis** [comment]
Yes.
Play around with the "Key" of each sharedpref value. Different keys for different user would mean each user can have different accounts. You are currently using a single key for all users which makes a new signup overwrite the existing one.

**Comment by khadijatbakare** [comment]
can we also used the accountmanager instead of using the keys of the shared pref

**Comment by segunfrancis** [comment]
I really can't tell what you mean by "accountmanager", can you shed more light?
But the feature I requested can definitely be achieved by giving each user unique shared preference keys
